# NumPy

In [1]:
import numpy as np

## Creando arreglos (array)

In [3]:
arreglo1d = np.array([1, 2, 3])
arreglo1d, type(arreglo1d)

(array([1, 2, 3]), numpy.ndarray)

In [6]:
array2d = np.array([[1, 2, 3],
                    [0.8, 0.6, 1.9]])
array2d, type(array2d)

(array([[1. , 2. , 3. ],
        [0.8, 0.6, 1.9]]), numpy.ndarray)

In [7]:
array3d = np.array([[[1, 2, 3],
                     [4, 5, 6]], 
                    [[1, 2, 3],
                     [4, 5, 6]]])
array3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

<img src="https://drive.google.com/uc?export=download&id=1hFn-FZ8BsX1sETj6-fa92OHeG5ZAqOtA" width="800">

In [8]:
arreglo1d.shape, array2d.shape, array3d.shape

((3,), (2, 3), (2, 2, 3))

In [9]:
arreglo1d.ndim, array2d.ndim, array3d.ndim

(1, 2, 3)

In [10]:
arreglo1d.size, array2d.size, array3d.size

(3, 6, 12)

In [11]:
# arreglos con solo unos
array_unos = np.ones((5, 7))
array_unos

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [13]:
# arreglos con solo ceros
array_ceros = np.zeros((5, 7, 4))
array_ceros

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
#arreglos con valores aleatorios dentro de un rango
array_random = np.arange(0, 10, 2)
array_random

array([0, 2, 4, 6, 8])

In [16]:
array_random2 = np.random.randint(0, 10, size=(3, 7))
array_random2

array([[3, 0, 6, 1, 4, 5, 4],
       [3, 8, 2, 4, 9, 2, 3],
       [6, 5, 5, 2, 5, 1, 5]])

In [21]:
array_random3 = np.random.random(size=(3, 7))
array_random3

array([[0.52916002, 0.10265108, 0.52763102, 0.89086763, 0.84846699,
        0.51597209, 0.54531613],
       [0.98291551, 0.73385844, 0.97166466, 0.98774777, 0.98884907,
        0.32023066, 0.72551857],
       [0.61654835, 0.26140333, 0.92605854, 0.12421729, 0.94801744,
        0.39192675, 0.38408637]])

In [31]:
# utilizando la funcion seed (semilla)
np.random.seed(0)
array_random4 = np.random.random(size=(3, 7))
array_random4

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
        0.64589411, 0.43758721],
       [0.891773  , 0.96366276, 0.38344152, 0.79172504, 0.52889492,
        0.56804456, 0.92559664],
       [0.07103606, 0.0871293 , 0.0202184 , 0.83261985, 0.77815675,
        0.87001215, 0.97861834]])

## Operaciones con arreglos (array)

In [38]:
np.random.seed(0)
array1 = np.random.randint(10, size=(2, 2))
array1, array1.shape

(array([[5, 0],
        [3, 3]]), (2, 2))

In [39]:
np.random.seed(10)
array2 = np.random.randint(10, size=(2, 2))
array2, array2.shape

(array([[9, 4],
        [0, 1]]), (2, 2))

In [40]:
array3 = array1 + array2
array3

array([[14,  4],
       [ 3,  4]])

In [41]:
np.random.seed(5)
array4 = np.random.randint(10, size=(2, 2, 3))
array4

array([[[3, 6, 6],
        [0, 9, 8]],

       [[4, 7, 0],
        [0, 7, 1]]])

In [42]:
array5 = array2 * array4
array5

ValueError: ignored

## Reshape

In [43]:
array2.shape, array4.shape

((2, 2), (2, 2, 3))

In [44]:
array2_reshape = array2.reshape(2, 2, 1)
array2_reshape

array([[[9],
        [4]],

       [[0],
        [1]]])

In [45]:
array2_reshape.shape

(2, 2, 1)

In [46]:
array5 = array2_reshape * array4
array5

array([[[27, 54, 54],
        [ 0, 36, 32]],

       [[ 0,  0,  0],
        [ 0,  7,  1]]])

## Transpose

In [47]:
np.random.seed(8)
array6 = np.random.randint(10, size=(2, 5))
array6

array([[3, 4, 1, 9, 5],
       [8, 3, 8, 0, 5]])

In [48]:
array7 = array6.T
array7

array([[3, 8],
       [4, 3],
       [1, 8],
       [9, 0],
       [5, 5]])

In [49]:
array7.shape

(5, 2)

## Comparaciones

In [50]:
np.random.seed(7)
array8 = np.random.randint(10, size=(2, 5))
array8

array([[4, 9, 6, 3, 3],
       [7, 7, 9, 7, 8]])

In [51]:
np.random.seed(6)
array9 = np.random.randint(10, size=(2, 5))
array9

array([[9, 3, 4, 0, 9],
       [1, 9, 1, 4, 1]])

In [53]:
array8 >= array9

array([[False,  True,  True,  True, False],
       [ True, False,  True,  True,  True]])

In [54]:
array8 > 5

array([[False,  True,  True, False, False],
       [ True,  True,  True,  True,  True]])

## Ordenamiento de array

In [55]:
array8

array([[4, 9, 6, 3, 3],
       [7, 7, 9, 7, 8]])

In [56]:
np.sort(array8)

array([[3, 3, 4, 6, 9],
       [7, 7, 7, 8, 9]])